//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoDesempenio
    {
        public System.Guid IDAlumno { get; set; }
        public string IDUsuario { get; set; }
        public long Bimestre { get; set; }
        public System.Guid IDGrupo { get; set; }
        public Nullable<double> PromedioAsistencia { get; set; }
        public string ColorAsistencia { get; set; }
        public Nullable<double> PromedioTrabajo { get; set; }
        public string ColorTrabajo { get; set; }
        public Nullable<double> PromedioPortafolio { get; set; }
        public string ColorPortafolio { get; set; }
        public Nullable<double> PromedioExamen { get; set; }
        public string ColorExamen { get; set; }
        public Nullable<double> PromedioDiagnostico { get; set; }
        public string ColorDiagnostico { get; set; }
        public Nullable<double> PromedioPortafolioEsquemaMapa { get; set; }
        public Nullable<double> PromedioPortafolioExposicion { get; set; }
        public Nullable<double> PromedioPortafolioGuiaObservacion { get; set; }
        public Nullable<double> PromedioPortafolioListaCotejo { get; set; }
        public Nullable<double> PromedioPortafolioLineaTiempo { get; set; }
        public Nullable<double> PromedioPortafolioMapaAprendisaje { get; set; }
        public Nullable<double> PromedioPortafolioPortafolio { get; set; }
        public Nullable<double> PromedioPortafolioProducciones { get; set; }
        public Nullable<double> PromedioPortafolioProyecto { get; set; }
        public Nullable<double> PromedioPortafolioRegistroAnecdotico { get; set; }
        public Nullable<double> PromedioPortafolioRevisionCuadernos { get; set; }
        public Nullable<double> PromedioPortafolioRubrica { get; set; }
        public Nullable<double> PromedioExamenParcial { get; set; }
        public Nullable<double> PromedioExamenBimestral { get; set; }
        public Nullable<double> PromedioExamenRecuperacion { get; set; }
        public Nullable<double> PromedioExamenDiagnostico { get; set; }
        public Nullable<int> TotalAsistencias { get; set; }
        public Nullable<int> TotalFaltas { get; set; }
        public Nullable<double> TotalTrabajosCumplidos { get; set; }
        public Nullable<double> TotalTrabajosNoCumplidos { get; set; }
        public Nullable<double> PromedioHabilidadAutoevaluacion { get; set; }
        public Nullable<double> PromedioHabilidadCoevaluacion { get; set; }
        public Nullable<int> TotalTrabajosMedios { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
