//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credencial
    {
        public string IDCredencial { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public string IDUsuarioBeneficiario { get; set; }
        public string IDUsuarioPaga { get; set; }
        public bool Activo { get; set; }
        public bool EsPrincipal { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaPagada { get; set; }

        internal static void renovar()
        {
            throw new NotImplementedException();
        }
    }
}
