//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticoCicloTema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnosticoCicloTema()
        {
            this.DiagnosticoCicloAlumno = new HashSet<DiagnosticoCicloAlumno>();
        }
    
        public System.Guid IDTema { get; set; }
        public System.Guid IDDiagnosticoCiclo { get; set; }
        public string Nombre { get; set; }
        public int Reactivos { get; set; }
        public string Respuesta { get; set; }
        public string TipoTema { get; set; }
        public string Archivo { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta1 { get; set; }
        public string Respuesta2 { get; set; }
        public string Instrucciones { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual DiagnosticoCiclo DiagnosticoCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosticoCicloAlumno> DiagnosticoCicloAlumno { get; set; }
    }
}
