//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticoPsicologico
    {
        public System.Guid IDAlumno { get; set; }
        public System.Guid IDGrupo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string Regular { get; set; }
        public string NEE { get; set; }
        public string Talentos { get; set; }
        public string SituacionRiesgo { get; set; }
        public string Necesidades { get; set; }
        public string Linguistica { get; set; }
        public string LogicoMatematica { get; set; }
        public string VisualEspacial { get; set; }
        public string KinestesicaCorporal { get; set; }
        public string Musical { get; set; }
        public string Intrapersonal { get; set; }
        public string Interpersonal { get; set; }
        public string MuestraIniciativa { get; set; }
        public string RequiereApoyo { get; set; }
        public string Motivado { get; set; }
        public string Aburrimiento { get; set; }
        public string Indiferencia { get; set; }
        public string Temeroso { get; set; }
        public string ConductaInadecuada { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string FamiliaCompleta { get; set; }
        public string FamiliaMonoparental { get; set; }
        public string ViveOtros { get; set; }
        public Nullable<int> Hermanos { get; set; }
        public string LugarFamilia { get; set; }
        public string MuestraInteresHijo { get; set; }
        public string ParticipaActividadesEscuela { get; set; }
        public string ReconoceValia { get; set; }
        public string ExpresaEmociones { get; set; }
        public string RespetaAsiMismo { get; set; }
        public string ResuelveConfilctos { get; set; }
        public string RespetaReglas { get; set; }
        public string CuentaConCasa { get; set; }
        public string TieneComputadora { get; set; }
        public string ComoSeTranslada { get; set; }
        public string ServicioMedico { get; set; }
        public string EscolaridadPadres { get; set; }
        public string EtapaSesioromotora { get; set; }
        public string EtapaPreconvencional { get; set; }
        public string OperacionesContretas { get; set; }
        public string OperacionesFormales { get; set; }
        public string MoralidadPreconvencional { get; set; }
        public string MoralidadConvencional { get; set; }
        public string MoralidadPrincipiosAutonomos { get; set; }
        public string ConfianzaDesconfianza { get; set; }
        public string AutonomiaVerguenza { get; set; }
        public string IniciativaCulpa { get; set; }
        public string Laboriosidad { get; set; }
        public string IdentidadConfusion { get; set; }
        public string IntimidadAislamiento { get; set; }
        public string Generabilidad { get; set; }
        public string Integridad { get; set; }
        public string EvaluacionBloque1 { get; set; }
        public string EvaluacionBloque2 { get; set; }
        public string EvaluacionBloque3 { get; set; }
        public string EvaluacionBloque4 { get; set; }
        public string EvaluacionBloque5 { get; set; }
        public string ProgramaBloque1 { get; set; }
        public string ProgramaBloque2 { get; set; }
        public string ProgramaBloque3 { get; set; }
        public string ProgramaBloque4 { get; set; }
        public string ProgramaBloque5 { get; set; }
        public string CTE10 { get; set; }
        public string CTE8 { get; set; }
        public string CTE5 { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
