//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examen()
        {
            this.ExamenTema = new HashSet<ExamenTema>();
        }
    
        public System.Guid IDExamen { get; set; }
        public System.Guid IDBimestre { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Bimestres Bimestres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenTema> ExamenTema { get; set; }
    }
}
