//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Alumno = new HashSet<Alumno>();
            this.AlumnoDesempenio = new HashSet<AlumnoDesempenio>();
            this.Bimestres = new HashSet<Bimestres>();
            this.DiagnosticoPsicologico = new HashSet<DiagnosticoPsicologico>();
            this.HabilidadesAlumno = new HashSet<HabilidadesAlumno>();
            this.Sesion = new HashSet<Sesion>();
            this.Portafolio = new HashSet<Portafolio>();
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public System.Guid IDGrupo { get; set; }
        public string Descripcion { get; set; }
        public string IDUsuario { get; set; }
        public string Materia { get; set; }
        public string Grado { get; set; }
        public string Grupo { get; set; }
        public string Escuela { get; set; }
        public string RegistroFederalEscolar { get; set; }
        public string Turno { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Status { get; set; }
        public string Color { get; set; }
        public string Ciclo { get; set; }
        public Nullable<bool> EsTaller { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno> Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoDesempenio> AlumnoDesempenio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bimestres> Bimestres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosticoPsicologico> DiagnosticoPsicologico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesAlumno> HabilidadesAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesion> Sesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portafolio> Portafolio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}
