//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabilidadesAlumno
    {
        public System.Guid IDHabilidadAlumno { get; set; }
        public Nullable<System.Guid> IDAlumno { get; set; }
        public Nullable<System.Guid> IDGrupo { get; set; }
        public Nullable<System.Guid> IDBimestre { get; set; }
        public Nullable<int> Autoevaluacion { get; set; }
        public Nullable<int> Coevaluacion { get; set; }
        public string Comprension { get; set; }
        public string Conocimiento { get; set; }
        public string Sintesis { get; set; }
        public string Argumentacion { get; set; }
        public Nullable<int> ApoyoLectura { get; set; }
        public Nullable<int> ApoyoEscritura { get; set; }
        public Nullable<int> ApoyoMatematicas { get; set; }
        public Nullable<bool> SeInvolucraClase { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Bimestres Bimestres { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
