//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortafolioAlumno
    {
        public System.Guid IDPortafolioAlumno { get; set; }
        public Nullable<System.Guid> IDPortafolio { get; set; }
        public Nullable<System.Guid> IDAlumno { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Aspecto1 { get; set; }
        public string Aspecto2 { get; set; }
        public string Aspecto3 { get; set; }
        public string Aspecto4 { get; set; }
        public string Aspecto5 { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
        public Nullable<int> Calificacion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Portafolio Portafolio { get; set; }
    }
}
