//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortafolioAlumno
    {
        public System.Guid IDPortafolioAlumno { get; set; }
        public Nullable<System.Guid> IDPortafolio { get; set; }
        public Nullable<System.Guid> IDAlumno { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Aspecto1 { get; set; }
        public string Aspecto2 { get; set; }
        public string Aspecto3 { get; set; }
        public string Aspecto4 { get; set; }
        public string Aspecto5 { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Portafolio Portafolio { get; set; }
    }
}
