//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portafolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Portafolio()
        {
            this.PortafolioAlumno = new HashSet<PortafolioAlumno>();
        }
    
        public System.Guid IDPortafolio { get; set; }
        public Nullable<System.Guid> IDGrupo { get; set; }
        public Nullable<System.Guid> IDBimestre { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string TipoTrabajo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Aspecto1 { get; set; }
        public string Criterio1 { get; set; }
        public string Aspecto2 { get; set; }
        public string Criterio2 { get; set; }
        public string Aspecto3 { get; set; }
        public string Criterio3 { get; set; }
        public string Aspecto4 { get; set; }
        public string Criterio4 { get; set; }
        public string Aspecto5 { get; set; }
        public string Criterio5 { get; set; }
        public bool Activo1 { get; set; }
        public bool Activo2 { get; set; }
        public bool Activo3 { get; set; }
        public bool Activo4 { get; set; }
        public bool Activo5 { get; set; }
        public string Observacion1 { get; set; }
        public string Observacion2 { get; set; }
        public string Observacion3 { get; set; }
        public string Observacion4 { get; set; }
        public string Observacion5 { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.Guid> IDTipoPortafolio { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
        public Nullable<double> Reactivo1 { get; set; }
        public Nullable<double> Reactivo2 { get; set; }
        public Nullable<double> Reactivo3 { get; set; }
        public Nullable<double> Reactivo4 { get; set; }
        public Nullable<double> Reactivo5 { get; set; }
        public Nullable<double> Reactivo6 { get; set; }
    
        public virtual Bimestres Bimestres { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual TipoPortafolio TipoPortafolio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortafolioAlumno> PortafolioAlumno { get; set; }
    }
}
