//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortafolioDefecto
    {
        public System.Guid IDPortafolioDefecto { get; set; }
        public string Nombre { get; set; }
        public string TipoTrabajo { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Aspecto1 { get; set; }
        public string Criterio1 { get; set; }
        public string Aspecto2 { get; set; }
        public string Criterio2 { get; set; }
        public string Aspecto3 { get; set; }
        public string Criterio3 { get; set; }
        public string Aspecto4 { get; set; }
        public string Criterio4 { get; set; }
        public string Aspecto5 { get; set; }
        public string Criterio5 { get; set; }
        public bool Activo1 { get; set; }
        public bool Activo2 { get; set; }
        public bool Activo3 { get; set; }
        public bool Activo4 { get; set; }
        public bool Activo5 { get; set; }
        public string Observacion1 { get; set; }
        public string Observacion2 { get; set; }
        public string Observacion3 { get; set; }
        public string Observacion4 { get; set; }
        public string Observacion5 { get; set; }
        public string Tipo { get; set; }
        public string IDUsuario { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
