//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaExamen
    {
        public System.Guid IDPregunta { get; set; }
        public System.Guid IDTema { get; set; }
        public string Pregunta { get; set; }
    
        public virtual ExamenTema ExamenTema { get; set; }
    }
}
