//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sesion()
        {
            this.AlumnoSesion = new HashSet<AlumnoSesion>();
        }
    
        public System.Guid IDSesion { get; set; }
        public System.Guid IDGrupo { get; set; }
        public System.Guid IDBimestre { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaActualiacion { get; set; }
        public string Observacion { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoSesion> AlumnoSesion { get; set; }
        public virtual Bimestres Bimestres { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
