//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMTDevEntities : DbContext
    {
        public SMTDevEntities()
            : base("name=SMTDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credencial> Credencial { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<PortafolioDefecto> PortafolioDefecto { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoDesempenio> AlumnoDesempenio { get; set; }
        public virtual DbSet<AlumnoSesion> AlumnoSesion { get; set; }
        public virtual DbSet<Bimestres> Bimestres { get; set; }
        public virtual DbSet<DiagnosticoCiclo> DiagnosticoCiclo { get; set; }
        public virtual DbSet<DiagnosticoCicloAlumno> DiagnosticoCicloAlumno { get; set; }
        public virtual DbSet<DiagnosticoCicloTema> DiagnosticoCicloTema { get; set; }
        public virtual DbSet<DiagnosticoPsicologico> DiagnosticoPsicologico { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<ExamenAlumno> ExamenAlumno { get; set; }
        public virtual DbSet<ExamenTema> ExamenTema { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<HabilidadesAlumno> HabilidadesAlumno { get; set; }
        public virtual DbSet<Portafolio> Portafolio { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<TipoPortafolio> TipoPortafolio { get; set; }
        public virtual DbSet<Trabajo> Trabajo { get; set; }
        public virtual DbSet<TrabajoAlumno> TrabajoAlumno { get; set; }
        public virtual DbSet<TutorAlumno> TutorAlumno { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<PortafolioAlumno> PortafolioAlumno { get; set; }
        public virtual DbSet<PreguntaExamen> PreguntaExamen { get; set; }
    }
}
