//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajo()
        {
            this.TrabajoAlumno = new HashSet<TrabajoAlumno>();
        }
    
        public System.Guid IDTrabajo { get; set; }
        public Nullable<System.Guid> IDGrupo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.Guid> IDBimestre { get; set; }
        public string Observaciones { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Actividad { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Bimestres Bimestres { get; set; }
        public virtual Grupos Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoAlumno> TrabajoAlumno { get; set; }
    }
}
