//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMT.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoAlumno
    {
        public System.Guid IDTrabajoAlumno { get; set; }
        public Nullable<System.Guid> IDTrabajo { get; set; }
        public Nullable<System.Guid> IDAlumno { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public System.DateTimeOffset FechaSync { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Trabajo Trabajo { get; set; }
    }
}
